version: '3.8'

services:
  db:
    image: mysql:8.0.38
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: local
    networks:
      - wordpress-network

  wordpress:
    image: wordpress:6.5.5-php8.1-fpm-alpine
    container_name: wordpress
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: db
    depends_on:
      - db
    networks:
      - wordpress-network

  nginx:
    image: nginx:1.27.0-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
      - ./wordpress:/var/www/html
      - ./nginx/html/.well-known:/var/www/certbot/.well-known
    depends_on:
      - wordpress
    networks:
      - wordpress-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_data:/var/www/certbot
      - ./nginx:/etc/nginx/conf.d
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --deploy-hook \"nginx -s reload\"; sleep 12h; done'"
    networks:
      - wordpress-network

networks:
  wordpress-network:

volumes:
  db_data:
  certbot_certs:
  certbot_data: